module.exports = {
  extends: 'eslint:recommended',
  rules: {
    indent: ['error', 2, { SwitchCase: 1 }],
    'no-tabs': 'error',
    curly: 'error',
    'comma-dangle': ['warn', 'always-multiline'],
    quotes: ['warn', 'single', { avoidEscape: true }],
    'no-extra-semi': 'error',
    'linebreak-style': ['error', 'unix'],
    'no-unused-vars': 'warn',
    'no-console': ['warn', { allow: ['warn', 'error', 'info'] }],
    'new-cap': 'error',
    'no-underscore-dangle': [
      'error',
      {
        allow: ['_id', '_execute', '__basedir'],
        allowAfterThis: true,
        allowAfterSuper: true,
        allowAfterThisConstructor: true,
        enforceInMethodNames: false,
      },
    ],
    'max-len': ['error', { code: 150 }],
    'no-param-reassign': ['error', { props: false }],
    'object-curly-newline': ['warn', { multiline: true }],
    'no-use-before-define': ['error', { functions: false }],
    'array-element-newline': [
      'warn',
      {
        ArrayExpression: 'consistent',
        ArrayPattern: { minItems: 3 },
      },
    ],
    'no-warning-comments': [
      'warn',
      {
        terms: ['todo', 'fix', 'fixme', 'perf'],
        location: 'anywhere',
      },
    ],
    'arrow-parens': ['off', 'as-needed'],
    'no-plusplus': 'off',
    camelcase: [
      'error',
      {
        properties: 'always',
        ignoreDestructuring: false,
        ignoreImports: false,
      },
    ],
    // Règles liées à la sécurité
    'no-eval': 'error',
    'no-implied-eval': 'error',
    'no-new-func': 'error',
    'no-script-url': 'error',
    'no-useless-catch': 'error',
    'no-unused-labels': 'error',
    'no-undefined': 'error',
    'require-await': 'error',
    'valid-typeof': 'error',
    'no-await-in-loop': 'warn',
    'no-template-curly-in-string': 'error',
    'no-unsafe-negation': 'error',
    'no-prototype-builtins': 'error',
    'no-global-assign': 'error',
    'no-new-wrappers': 'error',
    'no-octal-escape': 'error',
    'no-self-compare': 'error',
    'no-unmodified-loop-condition': 'error',
    'no-unused-expressions': 'error',
    'no-void': 'error',
    'no-with': 'error',
    'no-useless-concat': 'error',
    'no-var': 'error',
    'prefer-const': 'error',
    'prefer-promise-reject-errors': 'error',
    'import/extensions': ['warn', 'ignorePackages'],
  },
};
